#-------------------------------------------------------------------------------
#-- NOTE: THIS FILE SHALL NOT BE MODIFIED.
#-------------------------------------------------------------------------------


################################################################################
# (Coaxlink Octo) CustomLogic design common location constraints
################################################################################

# Oscillator
set_property PACKAGE_PIN AA13 [get_ports osc_125M_p]
set_property IOSTANDARD BLVDS_25 [get_ports osc_125M_p]

# CoaXPress
set_property PACKAGE_PIN M6 [get_ports cxph_gth_clk_p]
# Bracket upper connectors
set_property PACKAGE_PIN A4 [get_ports {cxph_rx_p[0]}]
set_property PACKAGE_PIN B2 [get_ports {cxph_rx_p[1]}]
set_property PACKAGE_PIN C4 [get_ports {cxph_rx_p[2]}]
set_property PACKAGE_PIN D2 [get_ports {cxph_rx_p[3]}]
set_property PACKAGE_PIN AA10 [get_ports {cxph_tx[0]}]
set_property PACKAGE_PIN AA9 [get_ports {cxph_tx[1]}]
set_property PACKAGE_PIN AB10 [get_ports {cxph_tx[2]}]
set_property PACKAGE_PIN AB9 [get_ports {cxph_tx[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cxph_tx[*]}]

# Fan
set_property PACKAGE_PIN J11 [get_ports fanspeed]
set_property PACKAGE_PIN AF15 [get_ports fanpwm]
set_property IOSTANDARD LVCMOS15 [get_ports fanspeed]
set_property IOSTANDARD LVCMOS33 [get_ports fanpwm]

# Status
set_property PACKAGE_PIN H14 [get_ports status_ledg]
set_property PACKAGE_PIN G14 [get_ports status_ledr]
set_property IOSTANDARD LVCMOS15 [get_ports status_ledg]
set_property IOSTANDARD LVCMOS15 [get_ports status_ledr]
set_property DRIVE 4 [get_ports status_ledg]
set_property DRIVE 4 [get_ports status_ledr]

# I/Os
set_property PACKAGE_PIN G10 [get_ports {csync[1]}]
set_property PACKAGE_PIN G9 [get_ports {csync[2]}]
set_property PACKAGE_PIN H12 [get_ports {csync[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {csync[*]}]
set_property DRIVE 8 [get_ports {csync[*]}]
# I/O Set 1
set_property PACKAGE_PIN AD14 [get_ports {ttlio1_data[1]}]
set_property PACKAGE_PIN AC14 [get_ports {ttlio1_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ttlio1_data[*]}]
set_property DRIVE 4 [get_ports {ttlio1_data[*]}]
set_property PACKAGE_PIN AD13 [get_ports {ttlio1_dir[1]}]
set_property PACKAGE_PIN AC13 [get_ports {ttlio1_dir[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ttlio1_dir[*]}]
set_property DRIVE 4 [get_ports {ttlio1_dir[*]}]
set_property PACKAGE_PIN AA15 [get_ports {iout1[1]}]
set_property PACKAGE_PIN AB15 [get_ports {iout1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iout1[*]}]
set_property PACKAGE_PIN AA14 [get_ports {iin1[1]}]
set_property PACKAGE_PIN AB14 [get_ports {iin1[2]}]
set_property PACKAGE_PIN W15 [get_ports {iin1[3]}]
set_property PACKAGE_PIN Y15 [get_ports {iin1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iin1[*]}]
set_property PACKAGE_PIN W14 [get_ports {din1[1]}]
set_property PACKAGE_PIN W13 [get_ports {din1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din1[*]}]
# I/O Extension
set_property PACKAGE_PIN Y13 [get_ports {io_ext1_1wire}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_ext1_1wire}]
set_property PACKAGE_PIN AE12 [get_ports {io_ext1[1]}]
set_property PACKAGE_PIN AF12 [get_ports {io_ext1[2]}]
set_property PACKAGE_PIN AD15 [get_ports {io_ext1[3]}]
set_property PACKAGE_PIN AE15 [get_ports {io_ext1[4]}]
set_property PACKAGE_PIN AF14 [get_ports {io_ext1[5]}]
set_property PACKAGE_PIN AF13 [get_ports {io_ext1[6]}]
set_property PACKAGE_PIN AE13 [get_ports {io_ext1[7]}]
set_property PACKAGE_PIN AE16 [get_ports {io_ext1[8]}]
set_property PACKAGE_PIN AC12 [get_ports {io_ext1[9]}]
set_property PACKAGE_PIN AC11 [get_ports {io_ext1[10]}]
set_property PACKAGE_PIN AB12 [get_ports {io_ext1[11]}]
set_property PACKAGE_PIN AB11 [get_ports {io_ext1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_ext1[*]}]
# I/O Expander
set_property PACKAGE_PIN W11 [get_ports pocled_l_scl]
set_property PACKAGE_PIN W10 [get_ports pocled_l_sda]
set_property IOSTANDARD LVCMOS33 [get_ports pocled_l_scl]
set_property IOSTANDARD LVCMOS33 [get_ports pocled_l_sda]
set_property DRIVE 4 [get_ports pocled_l_scl]
set_property DRIVE 4 [get_ports pocled_l_sda]

# PoC Ctrl
set_property PACKAGE_PIN Y11 [get_ports poc_scl]
set_property PACKAGE_PIN AA8 [get_ports poc_sda]
set_property PACKAGE_PIN Y10 [get_ports poc_alert]
set_property IOSTANDARD LVCMOS33 [get_ports poc_scl]
set_property IOSTANDARD LVCMOS33 [get_ports poc_sda]
set_property IOSTANDARD LVCMOS33 [get_ports poc_alert]
set_property DRIVE 4 [get_ports poc_scl]
set_property DRIVE 4 [get_ports poc_sda]
set_property PACKAGE_PIN A13 [get_ports peg_prst_12v]
set_property PACKAGE_PIN V11 [get_ports vps24_pg]
set_property PACKAGE_PIN Y8 [get_ports en_vps24]
set_property IOSTANDARD LVCMOS15 [get_ports peg_prst_12v]
set_property IOSTANDARD LVCMOS33 [get_ports vps24_pg]
set_property IOSTANDARD LVCMOS33 [get_ports en_vps24]
set_property DRIVE 4 [get_ports en_vps24]

# Configuration
set_property PACKAGE_PIN AC16 [get_ports cfg_sda]
set_property PACKAGE_PIN AD16 [get_ports cfg_scl]
set_property PACKAGE_PIN AB16 [get_ports cfg_wp_n]
set_property IOSTANDARD LVCMOS33 [get_ports cfg_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cfg_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cfg_wp_n]
set_property DRIVE 4 [get_ports cfg_scl]
set_property DRIVE 4 [get_ports cfg_sda]
set_property DRIVE 4 [get_ports cfg_wp_n]
set_property PACKAGE_PIN AE18 [get_ports force_re_prog_n]
set_property IOSTANDARD LVCMOS33 [get_ports force_re_prog_n]
set_property DRIVE 4 [get_ports force_re_prog_n]
set_property PACKAGE_PIN AD23 [get_ports {cfg_clkout}]
set_property IOSTANDARD LVCMOS33 [get_ports {cfg_clkout}]
set_property PACKAGE_PIN AF19 [get_ports {cfg_fcs_n}] 
set_property IOSTANDARD LVCMOS33 [get_ports {cfg_fcs_n}]
set_property PACKAGE_PIN AD26 [get_ports {cfg_data[4]}]
set_property PACKAGE_PIN AE26 [get_ports {cfg_data[5]}]
set_property PACKAGE_PIN AF23 [get_ports {cfg_data[6]}]
set_property PACKAGE_PIN AF24 [get_ports {cfg_data[7]}]
set_property PACKAGE_PIN AE25 [get_ports {cfg_data[8]}]
set_property PACKAGE_PIN AF25 [get_ports {cfg_data[9]}]
set_property PACKAGE_PIN AE22 [get_ports {cfg_data[10]}]
set_property PACKAGE_PIN AF22 [get_ports {cfg_data[11]}]
set_property PACKAGE_PIN AD20 [get_ports {cfg_data[12]}]
set_property PACKAGE_PIN AD21 [get_ports {cfg_data[13]}]
set_property PACKAGE_PIN AB21 [get_ports {cfg_data[14]}]
set_property PACKAGE_PIN AC21 [get_ports {cfg_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cfg_data[*]}]
set_property PACKAGE_PIN AF20 [get_ports {lastbootbank}]
set_property IOSTANDARD LVCMOS33 [get_ports {lastbootbank}]
set_property PACKAGE_PIN AC9 [get_ports {pmaid[1]}]
set_property PACKAGE_PIN AD9 [get_ports {pmaid[2]}]
set_property PACKAGE_PIN AD11 [get_ports {pmaid[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmaid[*]}]


################################################################################
# (Coaxlink Octo) DDR4 IO Constraints
################################################################################
set_property PACKAGE_PIN T23 [get_ports c0_sys_clk_p]
set_property IOSTANDARD LVDS [get_ports c0_sys_clk_p]
set_property IOSTANDARD LVDS [get_ports c0_sys_clk_n]

set_property PACKAGE_PIN R21 [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN U20 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN T20 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN R20 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN R18 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN P19 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN U25 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN W24 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN T18 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN T19 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN P20 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN U21 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN U22 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN AB24 [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN T25 [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN P25 [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN P23 [get_ports {c0_ddr4_adr[16]}]

set_property PACKAGE_PIN R26 [get_ports {c0_ddr4_bg[0]}]
set_property PACKAGE_PIN R22 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN R23 [get_ports {c0_ddr4_ck_c[0]}]
set_property PACKAGE_PIN R25 [get_ports c0_ddr4_act_n]
set_property PACKAGE_PIN F24 [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN P21 [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN P24 [get_ports {c0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN T22 [get_ports {c0_ddr4_cke[0]}]

set_property PACKAGE_PIN V21 [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN P26 [get_ports {c0_ddr4_ba[1]}]

set_property PACKAGE_PIN AA24 [get_ports {c0_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN W23 [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN N23 [get_ports {c0_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN E25 [get_ports {c0_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN H22 [get_ports {c0_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN L18 [get_ports {c0_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN A24 [get_ports {c0_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN A22 [get_ports {c0_ddr4_dm_dbi_n[7]}]

set_property PACKAGE_PIN AB26 [get_ports {c0_ddr4_dq[0]}]
set_property PACKAGE_PIN AA23 [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN AC24 [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN Y23 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN AC23 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN AB22 [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN AC26 [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN AA22 [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN Y25 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN V24 [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN W25 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN W26 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN V23 [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN U24 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN Y26 [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN V22 [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN N26 [get_ports {c0_ddr4_dq[16]}]
set_property PACKAGE_PIN M26 [get_ports {c0_ddr4_dq[17]}]
set_property PACKAGE_PIN M24 [get_ports {c0_ddr4_dq[18]}]
set_property PACKAGE_PIN L24 [get_ports {c0_ddr4_dq[19]}]
set_property PACKAGE_PIN N22 [get_ports {c0_ddr4_dq[20]}]
set_property PACKAGE_PIN M22 [get_ports {c0_ddr4_dq[21]}]
set_property PACKAGE_PIN M25 [get_ports {c0_ddr4_dq[22]}]
set_property PACKAGE_PIN L25 [get_ports {c0_ddr4_dq[23]}]
set_property PACKAGE_PIN H24 [get_ports {c0_ddr4_dq[24]}]
set_property PACKAGE_PIN F25 [get_ports {c0_ddr4_dq[25]}]
set_property PACKAGE_PIN G26 [get_ports {c0_ddr4_dq[26]}]
set_property PACKAGE_PIN G25 [get_ports {c0_ddr4_dq[27]}]
set_property PACKAGE_PIN G24 [get_ports {c0_ddr4_dq[28]}]
set_property PACKAGE_PIN J24 [get_ports {c0_ddr4_dq[29]}]
set_property PACKAGE_PIN J25 [get_ports {c0_ddr4_dq[30]}]
set_property PACKAGE_PIN H26 [get_ports {c0_ddr4_dq[31]}]
set_property PACKAGE_PIN J23 [get_ports {c0_ddr4_dq[32]}]
set_property PACKAGE_PIN H21 [get_ports {c0_ddr4_dq[33]}]
set_property PACKAGE_PIN K23 [get_ports {c0_ddr4_dq[34]}]
set_property PACKAGE_PIN G22 [get_ports {c0_ddr4_dq[35]}]
set_property PACKAGE_PIN H19 [get_ports {c0_ddr4_dq[36]}]
set_property PACKAGE_PIN G21 [get_ports {c0_ddr4_dq[37]}]
set_property PACKAGE_PIN J21 [get_ports {c0_ddr4_dq[38]}]
set_property PACKAGE_PIN G20 [get_ports {c0_ddr4_dq[39]}]
set_property PACKAGE_PIN K20 [get_ports {c0_ddr4_dq[40]}]
set_property PACKAGE_PIN M21 [get_ports {c0_ddr4_dq[41]}]
set_property PACKAGE_PIN K21 [get_ports {c0_ddr4_dq[42]}]
set_property PACKAGE_PIN N21 [get_ports {c0_ddr4_dq[43]}]
set_property PACKAGE_PIN M19 [get_ports {c0_ddr4_dq[44]}]
set_property PACKAGE_PIN L19 [get_ports {c0_ddr4_dq[45]}]
set_property PACKAGE_PIN J19 [get_ports {c0_ddr4_dq[46]}]
set_property PACKAGE_PIN J20 [get_ports {c0_ddr4_dq[47]}]
set_property PACKAGE_PIN B24 [get_ports {c0_ddr4_dq[48]}]
set_property PACKAGE_PIN D24 [get_ports {c0_ddr4_dq[49]}]
set_property PACKAGE_PIN B26 [get_ports {c0_ddr4_dq[50]}]
set_property PACKAGE_PIN B25 [get_ports {c0_ddr4_dq[51]}]
set_property PACKAGE_PIN C24 [get_ports {c0_ddr4_dq[52]}]
set_property PACKAGE_PIN D25 [get_ports {c0_ddr4_dq[53]}]
set_property PACKAGE_PIN D26 [get_ports {c0_ddr4_dq[54]}]
set_property PACKAGE_PIN C26 [get_ports {c0_ddr4_dq[55]}]
set_property PACKAGE_PIN B21 [get_ports {c0_ddr4_dq[56]}]
set_property PACKAGE_PIN A20 [get_ports {c0_ddr4_dq[57]}]
set_property PACKAGE_PIN D21 [get_ports {c0_ddr4_dq[58]}]
set_property PACKAGE_PIN B20 [get_ports {c0_ddr4_dq[59]}]
set_property PACKAGE_PIN B22 [get_ports {c0_ddr4_dq[60]}]
set_property PACKAGE_PIN D20 [get_ports {c0_ddr4_dq[61]}]
set_property PACKAGE_PIN E21 [get_ports {c0_ddr4_dq[62]}]
set_property PACKAGE_PIN E20 [get_ports {c0_ddr4_dq[63]}]

set_property PACKAGE_PIN AA25 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN AB25 [get_ports {c0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN U26 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN V26 [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN K26 [get_ports {c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN J26 [get_ports {c0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN F22 [get_ports {c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN F23 [get_ports {c0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN L22 [get_ports {c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN K22 [get_ports {c0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN M20 [get_ports {c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN L20 [get_ports {c0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN D23 [get_ports {c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN C23 [get_ports {c0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN C21 [get_ports {c0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN C22 [get_ports {c0_ddr4_dqs_c[7]}]
